### ISSUE TITLE
ERROR when uploading gif

### ISSUE THREAD

**Issue by richylyq** [iAmGhost/gif2tgsticker#2]
this is the error i encountered

```bash
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "gif2tgsticker.py", line 99, in drop
  File "gif2tgsticker.py", line 126, in process_file
  File "ffmpeg\_probe.py", line 20, in probe
  File "subprocess.py", line 1022, in __init__
  File "subprocess.py", line 1491, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by iAmGhost** [comment]
Make sure ImageMagick with FFmpeg installed
(see https://github.com/iAmGhost/gif2tgsticker#windows)

**Comment by richylyq** [comment]
It was selected already @iAmGhost

**Comment by iAmGhost** [comment]
Seems installing FFmpeg along ImageMagick was insufficient(missing FFprobe). See updated README for installing FFmpeg.

**Comment by richylyq** [comment]
ar issue resolved.
thanks hyung
